name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: yarn lint -f ./.github/eslint-formatter-github.js

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: yarn run test --reporters=./.github/jest-github-reporter.js

      - name: Coverage Upload
        continue-on-error: true
        uses: codecov/codecov-action@v1
