name: lint

on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/checkout@v2
      - run: yarn install --immutable
      - run: yarn lint -f ./.github/eslint-formatter-github.js
