name: test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run test --reporters=./.github/jest-github-reporter.js
      - continue-on-error: true
        uses: codecov/codecov-action@v1
